import os
import json
from pathlib import Path

def generate_js_list():
    # Base directory of the script
    base_dir = Path(__file__).resolve().parent
    photos_dir = base_dir / "photos"
    output_file = base_dir / "photos_list.js"

    if not photos_dir.exists() or not photos_dir.is_dir():
        print(f"Error: 'photos' directory not found at {photos_dir}")
        return

    # Scan for files, excluding hidden files and folders
    files = [f for f in photos_dir.iterdir() if f.is_file() and not f.name.startswith(".")]
    
    # Sort files naturally (case-insensitive)
    files.sort(key=lambda x: x.name.lower())

    # Create lists of filenames
    full_names = [f.name for f in files]
    names_without_ext = [f.stem for f in files]

    # Generate the JavaScript content
    js_content = f"""// Generated by list_photos.py
// This file contains the list of files in the 'photos' folder.

// List of filenames with extensions
const photosWithExtension = {json.dumps(full_names, indent=4, ensure_ascii=False)};

// List of filenames without extensions (useful for search inputs like in the favorite automation script)
const photosWithoutExtension = {json.dumps(names_without_ext, indent=4, ensure_ascii=False)};

// Export options for node, ES modules, or global scope use
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = {{ photosWithExtension, photosWithoutExtension }};
}}
"""

    # Write to photos_list.js with UTF-8 encoding to preserve special characters
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"✅ Successfully processed {len(files)} files from the 'photos' folder!")
    print(f"💾 JS file written to: {output_file}")
    
    # Print previews to terminal
    print("\n--- Previews ---")
    print(f"const photosWithExtension = {json.dumps(full_names[:5], ensure_ascii=False)} ... (+ {len(full_names)-5} more)")
    print(f"const photosWithoutExtension = {json.dumps(names_without_ext[:5], ensure_ascii=False)} ... (+ {len(names_without_ext)-5} more)")

if __name__ == "__main__":
    generate_js_list()
